# Generated by Django 4.2 on 2023-05-02 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=40)),
                ('company_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=2)),
                ('invoice_currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=9)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Invoiced date')),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.user')),
            ],
        ),
    ]
